
from fastapi_pagination import Page, paginate, Params as pagination_params
from repositories.base import BaseRepository
from repositories.users import UsersRepository
from repositories.dealers import DealersRepository
from repositories.blogs import BlogsRepository, BlogMediaGroupsRepository
from repositories.show_rooms import ShowRoomsRepository
from repositories.brands import BrandsRepository
from repositories.categories import CategoriesRepository
from repositories.sub_categories import SubCategoriesRepository
from repositories.statuses import StatusesRepository

from repositories.resource_catalog.contacts import ContactsRepository
from repositories.resource_catalog.logos import LogosRepository
from repositories.resource_catalog.payment_methods import PaymentMethodsRepository
from repositories.resource_catalog.social_media import SocialMediaRepository
from repositories.resource_catalog.delivery import DeliveryRepository, DeliveryMediaRepository

#forms
from repositories.forms import BackCallWidgetsRepository, BackCallFormsRepository, WorkWithUsFormsRepository

from repositories.products import ProductsRepository, ProductMediaGroupsRepository

from repositories.orders import OrdersRepository

from repositories.tgclients import TgClientsRepository

from repositories.statistics import StatisticsOfOrdersRepository, StatisticsOfViewsRepository