from repositories import BaseRepository

class BackCallWidgetsRepository(BaseRepository):
    ...

class BackCallFormsRepository(BaseRepository):
    ...

class WorkWithUsFormsRepository(BaseRepository):
    ...

class LinkGoogleFormsRepository(BaseRepository):
    ...