"""basket

Revision ID: 2c8ff5f58d4d
Revises: 4582098d5f8d
Create Date: 2023-10-22 22:31:53.946993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c8ff5f58d4d'
down_revision: Union[str, None] = '4582098d5f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_tgclient_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'tgclient_id')
    op.add_column('orders_basket', sa.Column('tgclient_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders_basket', 'tgclients', ['tgclient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders_basket', type_='foreignkey')
    op.drop_column('orders_basket', 'tgclient_id')
    op.add_column('orders', sa.Column('tgclient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('orders_tgclient_id_fkey', 'orders', 'tgclients', ['tgclient_id'], ['id'])
    # ### end Alembic commands ###
