"""tgclients

Revision ID: 2ed79a051512
Revises: e6de1f6ed6d7
Create Date: 2023-10-12 02:22:47.240808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ed79a051512'
down_revision: Union[str, None] = 'e6de1f6ed6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tgclients',
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tgclients_id'), 'tgclients', ['id'], unique=False)
    op.add_column('orders', sa.Column('tgclient_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'tgclients', ['tgclient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'tgclient_id')
    op.drop_index(op.f('ix_tgclients_id'), table_name='tgclients')
    op.drop_table('tgclients')
    # ### end Alembic commands ###
