"""blogs

Revision ID: 369220800a2e
Revises: 86e481291421
Create Date: 2023-10-10 12:02:54.998461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '369220800a2e'
down_revision: Union[str, None] = '86e481291421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blog_media_groups_blog_id_fkey', 'blog_media_groups', type_='foreignkey')
    op.create_foreign_key(None, 'blog_media_groups', 'blogs', ['blog_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_media_groups', type_='foreignkey')
    op.create_foreign_key('blog_media_groups_blog_id_fkey', 'blog_media_groups', 'blogs', ['blog_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
