"""resource catalog

Revision ID: 36e759ba7712
Revises: 311d9f02a531
Create Date: 2023-10-10 16:24:07.322654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e759ba7712'
down_revision: Union[str, None] = '311d9f02a531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('filename', sa.String(), nullable=False))
    op.add_column('social_media', sa.Column('filename', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_media', 'filename')
    op.drop_column('contacts', 'filename')
    # ### end Alembic commands ###
