"""statistics

Revision ID: 3ace65869cc3
Revises: 2ed79a051512
Create Date: 2023-10-12 03:26:40.987787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ace65869cc3'
down_revision: Union[str, None] = '2ed79a051512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics_of_orders',
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistics_of_orders_id'), 'statistics_of_orders', ['id'], unique=False)
    op.create_table('statistics_of_views',
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistics_of_views_id'), 'statistics_of_views', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistics_of_views_id'), table_name='statistics_of_views')
    op.drop_table('statistics_of_views')
    op.drop_index(op.f('ix_statistics_of_orders_id'), table_name='statistics_of_orders')
    op.drop_table('statistics_of_orders')
    # ### end Alembic commands ###
