"""products

Revision ID: 5906d303e5d9
Revises: efea0cb65e5f
Create Date: 2023-10-11 03:45:14.737168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5906d303e5d9'
down_revision: Union[str, None] = 'efea0cb65e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('min_quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('uzb_price', sa.BigInteger(), nullable=False),
    sa.Column('usd_price', sa.BigInteger(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('video_link', sa.String(), nullable=True),
    sa.Column('tag', sa.Integer(), nullable=True),
    sa.Column('weight', sa.String(), nullable=True),
    sa.Column('clearance', sa.String(), nullable=True),
    sa.Column('fuel_tank_volume', sa.String(), nullable=True),
    sa.Column('fuel_consumption', sa.String(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('max_power', sa.String(), nullable=True),
    sa.Column('max_speed', sa.String(), nullable=True),
    sa.Column('ignition_system', sa.String(), nullable=True),
    sa.Column('gearbox', sa.String(), nullable=True),
    sa.Column('main_gear', sa.String(), nullable=True),
    sa.Column('front_lighting', sa.String(), nullable=True),
    sa.Column('back_lighting', sa.String(), nullable=True),
    sa.Column('front_brake', sa.String(), nullable=True),
    sa.Column('back_brake', sa.String(), nullable=True),
    sa.Column('front_tires', sa.String(), nullable=True),
    sa.Column('back_tires', sa.String(), nullable=True),
    sa.Column('sizes', sa.String(), nullable=True),
    sa.Column('show_on_main_page', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('show_on_see_also', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('amount_views', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('sub_category_id', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.ForeignKeyConstraint(['sub_category_id'], ['sub_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('product_media_groups',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_media_groups_id'), 'product_media_groups', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_media_groups_id'), table_name='product_media_groups')
    op.drop_table('product_media_groups')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
