"""forms

Revision ID: 6b82f1c9c0f5
Revises: 36e759ba7712
Create Date: 2023-10-10 17:05:45.892474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b82f1c9c0f5'
down_revision: Union[str, None] = '36e759ba7712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('back_call_forms',
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('known_from', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_back_call_forms_id'), 'back_call_forms', ['id'], unique=False)
    op.create_table('back_call_widgets',
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_back_call_widgets_id'), 'back_call_widgets', ['id'], unique=False)
    op.create_table('work_with_us_forms',
    sa.Column('about', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('known_from', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_with_us_forms_id'), 'work_with_us_forms', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_with_us_forms_id'), table_name='work_with_us_forms')
    op.drop_table('work_with_us_forms')
    op.drop_index(op.f('ix_back_call_widgets_id'), table_name='back_call_widgets')
    op.drop_table('back_call_widgets')
    op.drop_index(op.f('ix_back_call_forms_id'), table_name='back_call_forms')
    op.drop_table('back_call_forms')
    # ### end Alembic commands ###
