"""orders

Revision ID: 9ed578b0828c
Revises: 3ace65869cc3
Create Date: 2023-10-12 22:20:44.905690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ed578b0828c'
down_revision: Union[str, None] = '3ace65869cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('source', sa.String(), server_default='Bikeland.uz', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'source')
    # ### end Alembic commands ###
