"""linkToGoogleForms

Revision ID: 9f26265b849c
Revises: 1521dfeac0fc
Create Date: 2024-03-15 20:33:53.812220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f26265b849c'
down_revision: Union[str, None] = '1521dfeac0fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_google_form',
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('btn_name', sa.String(), nullable=False),
    sa.Column('btn_url', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_google_form_id'), 'link_google_form', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_google_form_id'), table_name='link_google_form')
    op.drop_table('link_google_form')
    # ### end Alembic commands ###
