"""cascade

Revision ID: ff557def8aa4
Revises: ccd6b36693ec
Create Date: 2023-12-15 01:09:05.464505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff557def8aa4'
down_revision: Union[str, None] = 'ccd6b36693ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_media_groups_product_id_fkey', 'product_media_groups', type_='foreignkey')
    op.create_foreign_key(None, 'product_media_groups', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_media_groups', type_='foreignkey')
    op.create_foreign_key('product_media_groups_product_id_fkey', 'product_media_groups', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
